### ISSUE TITLE
SacalWiki 的跑路 thread：牠要润啦

### ISSUE THREAD

**Issue by sacalWiki** [Yamabuki-bakery/galgamer#30]
目前退学在家，目标是在日本读带学然后就业

**Comment by Yamabuki-bakery** [comment]
報一下目標專業，目標學校，日語水平，設想的時間安排（大學一般是四月新學期開學），
注意不要自我出道

**Comment by sacalWiki** [comment]
目标专业 网络安全 ；目标学校 千叶大学 ；日语水平 N5 ；设想的时间安排  明年4月 or 7月读语言学校

**Comment by Yamabuki-bakery** [comment]
> 目标专业 网络安全 ；目标学校 千叶大学 ；日语水平 N5 ；设想的时间安排 明年4月 or 7月读语言学校

很好，我就在等你說出千葉大學這四個字，
因爲我莫名其妙地不知道爲甚麼就對千葉的印象很好，再加上我也申請過這所學校，
（根據 QS 大學娛樂排名顯示千葉大學跟我以前讀的大學的水平相差不是很遠，我就自以爲是地認爲千葉大學應該值得我碰瓷了一下）
我直接一波電話打過去給他們的某個教授，只不過牠們最後沒有收留俺，很可惜

**Comment by Yamabuki-bakery** [comment]
## 關於日語水平

對於大學學部生來說，日語水平十分重要，因爲你需要聽課，並且大學很可能會檢查你的日語水平
因此俺局得 N2 是比較保險的 level，應該努努力考出來，再不濟也應該有 N3.

不知道你有無報名今年 12 月的 JLPT？

日語證書應該儘量以最快的速度考出來，屬於有益無害，但是根據你的安排，如果明年讀語言學校，那麼你或許可以在日本考日語

**Comment by Yamabuki-bakery** [comment]
## 關於 JPUE 考試

官網： https://jpue.jp/

看起來很美好，在國內直接中文考試直接拿日本大學的 offer，而且千葉工學部也在參與名單裏面，
據說考試還簡單，一年有三次，中學會考水平，拿到初步 offer 以後，參加日語培訓，
培訓之後日語技能考試通過以後，就能正式錄取了，，，

中國區報名頁面進不去，按道理來說現在應該是報名時間，可能是因爲過於內卷已經爆滿，
感覺有點陰間，不過可以一試

目前只有香港區有考位

**Comment by Yamabuki-bakery** [comment]
## 關於千葉大學

招生簡章在此，請自己看 https://www.chiba-u.ac.jp/exam/gakubu/annai_boshu.html

同時，牠給了「留學生特別選拔」的流程圖

![image](https://user-images.githubusercontent.com/66236255/194855215-b51f3380-0b58-43f5-95cf-4b9f0fad1e2e.png)

https://www.chiba-u.ac.jp/e/admission/undergraduate/index.html

**Comment by Yamabuki-bakery** [comment]
牠說牠放棄了
